spring:
  cache:
    cache-names: customerFindByName
  profiles:
    active: dev

scheduling:
  printNumberOfCustomers: 3000

felles: felles verdi
---
spring:
  profiles: dev
egen: egen verdi i dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: prod
egen: egen verdi i prod