felles: felles verdi
scheduling:
  printNumberOfCustomers: 3000
spring:
  cache:
    cache-names: customerFindByName
---
spring:
  profiles: dev
egen: egen verdi i dev
---
spring:
  profiles: prod
egen: egen verdi i prod